name: Build Docker and Deploy to Cloud Run

on:
  push:
    branches:
      - add-deployment

env:
    REGION: us-east4
    IMAGE_NAME: app
    CLOUD_RUN_SERVICE: trashtalk-prod

jobs:
    build-docker:
        name: Build Docker Image and Save to Artifact
        runs-on: ubuntu-latest

        environment:
            name: production

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Google Authentication
              id: auth
              uses: google-github-actions/auth@v2
              with:
                  token_format: access_token
                  workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
                  service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

            - name: Login to Artifact Registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGION }}-docker.pkg.dev
                username: oauth2accesstoken
                password: ${{ steps.auth.outputs.access_token }}

            - name: Compute Image Tag
              id: meta
              run: |
                SHORT_SHA=${GITHUB_SHA::7}
                IMAGE_BASE="${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPOSITORY }}/${{ env.IMAGE_NAME }}"
                echo "TAGS=$IMAGE_BASE:sha-$SHORT_SHA,$IMAGE_BASE:latest" >> $GITHUB_OUTPUT

            - name: Set-up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push (dev)
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                provenance: false
                tags: ${{ steps.meta.outputs.TAGS }}
                cache-from: type=gha
                cache-to: type=gha,mode=max

            - name: Deploy to Cloud Run
              run: |
                IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest"

                gcloud run deploy ${{ env.CLOUD_RUN_SERVICE }} \
                  --image $IMAGE \
                  --region ${{ env.REGION }} \
                  --platform managed \
                  --allow-unauthenticated \
