name: Build Docker and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
    REGION: us-east4
    IMAGE_NAME: app
    CLOUD_RUN_SERVICE: trashtalk-prod

jobs:
    build-docker:
        name: Build Docker Image and Save to Artifact
        runs-on: ubuntu-latest

        environment:
            name: production

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Google Authentication
              id: auth
              uses: google-github-actions/auth@v2
              with:
                  token_format: access_token
                  workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
                  service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

            - name: Login to Artifact Registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGION }}-docker.pkg.dev
                username: oauth2accesstoken
                password: ${{ steps.auth.outputs.access_token }}

            - name: Compute Image Tag
              id: meta
              run: |
                SHORT_SHA=${GITHUB_SHA::7}
                IMAGE_BASE="${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPOSITORY }}/${{ env.IMAGE_NAME }}"
                echo "TAGS=$IMAGE_BASE:sha-$SHORT_SHA,$IMAGE_BASE:latest" >> $GITHUB_OUTPUT

            - name: Set-up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push (dev)
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                provenance: false
                tags: ${{ steps.meta.outputs.TAGS }}
                cache-from: type=gha
                cache-to: type=gha,mode=max
                build-args: |
                  NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
                  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
                  NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
                  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
                  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
                  NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
                  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}

            - name: Deploy to Cloud Run
              run: |
                IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest"

                gcloud run deploy ${{ env.CLOUD_RUN_SERVICE }} \
                  --image $IMAGE \
                  --region ${{ env.REGION }} \
                  --platform managed \
                  --allow-unauthenticated \
                  --set-secrets=FIREBASE_CLIENT_EMAIL=projects/${{ secrets.GCP_PROJECT_NUMBER }}/secrets/FIREBASE_CLIENT_EMAIL:latest \
                  --set-secrets=FIREBASE_PRIVATE_KEY=projects/${{ secrets.GCP_PROJECT_NUMBER }}/secrets/FIREBASE_PRIVATE_KEY:latest \
                  --set-secrets=FIREBASE_PROJECT_ID=projects/${{ secrets.GCP_PROJECT_NUMBER }}/secrets/FIREBASE_PROJECT_ID:latest \
                  --set-secrets=GEMINI_API_KEY=projects/${{ secrets.GCP_PROJECT_NUMBER }}/secrets/GEMINI_API_KEY:latest \
                  --set-secrets=GCP_MAPS_API_KEY=projects/${{ secrets.GCP_PROJECT_NUMBER }}/secrets/GCP_MAPS_API_KEY:latest \
                  --set-secrets=HUGGINGFACE_API_KEY=projects/${{ secrets.GCP_PROJECT_NUMBER }}/secrets/HUGGINGFACE_API_KEY:latest \
                  --set-secrets=NEXT_PUBLIC_FIREBASE_API_KEY=projects/${{ secrets.GCP_PROJECT_NUMBER }}/secrets/NEXT_PUBLIC_FIREBASE_API_KEY:latest \
                  --set-secrets=NEXT_PUBLIC_FIREBASE_APP_ID=projects/${{ secrets.GCP_PROJECT_NUMBER }}/secrets/NEXT_PUBLIC_FIREBASE_APP_ID:latest \
                  --set-secrets=NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=projects/${{ secrets.GCP_PROJECT_NUMBER }}/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:latest \
                  --set-secrets=NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=projects/${{ secrets.GCP_PROJECT_NUMBER }}/secrets/NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID:latest \
                  --set-secrets=NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=projects/${{ secrets.GCP_PROJECT_NUMBER }}/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:latest \
                  --set-secrets=NEXT_PUBLIC_FIREBASE_PROJECT_ID=projects/${{ secrets.GCP_PROJECT_NUMBER }}/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID:latest \
                  --set-secrets=NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=projects/${{ secrets.GCP_PROJECT_NUMBER }}/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:latest
